version: 1.0.{build}

init:
  -ps: |
    if (Test-Path C:\Projects) {
      Write-Host "Folder exists"
      exit 0
    } else {
      Write-Host "Folder doesn't exist"
      exit 1
    }
    if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }


build: off
  
