version: 1.0.{build}

test_script:
  - ps: |
      $ErrorActionPreference = "Stop"
      $path = "$env:SystemDrive\Projects"
      if (Test-Path $path) { throw "$path should not exist!" }

build: off
