version: 1.0.{build}

init:
  -ps: |
    if (Test-Path C:\Projects) {
      exit 1
    } else {
      exit 0
    }
    if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }


build: off
  
