version: 1.0.{build}

init:
  - ps: |
      $ErrorActionPreference = "Stop"
      $path = "$env:SystemDrive\Projects"
      if (Test-Path $path) { throw "$path should not exist!" }
      
      # bonus
      dir "$env:USERPROFILE"

build: off
