version: 1.0.{build}

init:
  - ps: |
      if (Test-Path -Path C:\Projectsxyz) {
        Write-Host "Folder exists"
        exit 1
      } else {
        Write-Host "Folder doesn't exist"
        exit 0
      }
      if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }


build: off
